"""
Django settings for gola_game project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from os.path import join, dirname

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

try:
    from dotenv import load_dotenv

    dotenv_path = join(BASE_DIR, '.env')
    load_dotenv(dotenv_path)
except ImportError:
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9t=&$t3rtv4p_a-*u^_je8qle*+h2$^m@r)(y=eht_35@l@88t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oauth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oauth.middleware.OAuthMiddleware',
]

ROOT_URLCONF = 'gola_game.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gola_game.wsgi.application'

AUTHLIB_OAUTH_CLIENTS = {
    'gitlab': {
        'client_id': os.environ['GL_CLIENT_ID'],
        'client_secret': os.environ['GL_CLIENT_SECRET'],
        'request_token_url': None,
        'request_token_params': None,
        'access_token_url': 'https://gitlab.com/oauth/token',
        'access_token_params': None,
        'refresh_token_url': None,
        'authorize_url': 'https://gitlab.com/oauth/authorize',
        'api_base_url': 'https://gitlab.com/api/v4/',
        'redirect_uri': os.environ['GL_APP_REDIRECT_URI'],
        'client_kwargs': {
            'scope': 'api read_user sudo read_repository read_registry openid',
            'token_endpoint_auth_method': 'client_secret_basic',
            'token_placement': 'header',
        }
    }
}

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
